### ISSUE TITLE
cut_kKaHyPar_sea20.ini is not found when package is installed

### ISSUE THREAD

**Issue by dmikushin** [alibaba/acqdp#11]
When package is installed in normal mode (without editable -e option), the `cut_kKaHyPar_sea20.ini` file is missing in the installation location:

```
$ python examples/circuit_simulation.py benchmark/circuit_n53_m10_s0_e0_pABCDCDAB.qsim
(3_w,7)-aCMA-ES (mu_w=2.3,w_1=58%) in dimension 3 (seed=519671471, Thu Dec 24 23:55:13 2020)
Could not load context file at: /home/dmitry/acqdp/venv/lib/python3.8/site-packages/acqdp-0.1.1-py3.8.egg/acqdp/tensor_network/kahypar_profiles/cut_kKaHyPar_sea20.ini
```

I guess, the reason is the file is not in the data section of the `setup.py`.

**Comment by digitofu** [comment]
Cannot reproduce this. Can you provide the following info?
- os and version
- exact commands you use to install
- pip and setuptools versions

**Comment by maxxungao** [comment]
Cannot reproduce this. Can you provide the following info?
- OS and version
- exact steps and commands to install it
- pip and setuptools versions

**Comment by maxxungao** [comment]
Turned out this can happen when installing using "python setup.py install". It installs the package as a zipped egg file so the program cannot find the individual .ini file. Setting zip_safe to false in setup.py would fix this.
