### ISSUE TITLE
Could you add more detailed example of how to use getDeployPlugin() feature?

### ISSUE THREAD

**Issue by Z-Y00** [alibaba/acqdp#14]
Hi, in file acqdp/tensor_network/contractor.py there is a function to import "tensor_network" submodule.
I'm wondering if this is the way you utilized GPU devices in your paper.
If that GPU library is available on the internet, could you add some document about what it is and how to use it?

**Comment by cupjinhuang** [comment]
In our implementation, we used JAX for GPU acceleration, which should be automatically included during setup. To utilize GPU, one can modify the corresponding configuration file (for example, `khp_params.json`) to
> 'contractor_params': {'backend': 'jax'}
This enables the runtime JAX support on GPU acceleration of tensor network contraction.

**Comment by Z-Y00** [comment]
thanks for your help!
