### ISSUE TITLE
visualization of the tensor graph and the contraction tree

### ISSUE THREAD

**Issue by Z-Y00** [alibaba/acqdp#15]
Hi, 
acqdp is a great software, thanks for building it and make it public.
I'm wondering if there is anyway to visualize the tensor graph and contraction tree.
Thanks a lot.

**Comment by cupjinhuang** [comment]
Hi,

Thank you very much for the inquiry. The visualization kit for the ACQDP is still under development yet. We will update on this thread as soon as this part is ready.

**Comment by Z-Y00** [comment]
thanks for your help!
