### ISSUE TITLE
How to perform a measurement in acqdp?

### ISSUE THREAD

**Issue by gtaifu** [alibaba/acqdp#20]
There are two classes (`Measurement` and `PureMeas`) in `circuit.py`. Since this simulator is based on tensor-network and density matrix, the effect of a measurement can be represented as a density-matrix update.  To my understanding, this is the method acqdp adopts.

In some cases, we are only interested in the state vector update, where a measurement collapses the state vector and returns a single bit representing the measurement result. How could we do this in acqdp?

Thanks!

**Comment by cupjinhuang** [comment]
Hello gtaifu,

We have added two methods `measure` and `collapse` in `acqdp.circuit.Circuit`.

The method `measure` of a circuit takes an argument specifying the index of the qubit to be measured, and returns a random measurement result and the corresponding conditional quantum state. Two optional arguments include `remove_qubit`, indicating whether the qubit being measured is to be removed from the system, and `collapse`, indicating whether the returned conditional state still preserves the tensor network structure.

The method `collapse` evaluates a quantum circuit as a tensor network, and replace the tensor network structure with the value of it. Doing this simplifies the quantum circuit and makes state vector update more efficient. `collapse` now only supports quantum circuits that are states, i.e. quantum operators with no input wires.

Please let us know if those functionalities meet your need.

**Comment by gtaifu** [comment]
@cupjinhuang thank you! I think it should work for us. I will integrate it into our open-source simulation platform ([pyqcisim](https://gitee.com/quingo/pyqcisim)). If there is any question, I will return to you!
