### ISSUE TITLE
ContractionTree.branch_info() returns empty list when slicing is applied

### ISSUE THREAD

**Issue by ChienKaiMa** [alibaba/acqdp#22]
I tried to simulate a 30-qubit GHZ state by ACQDP with slicing enabled, but an IndexError occurred.  I modified line 128 of `circuit_simulation.py` to `open_indices = [i for i in range(n)]`.  I found that `self.branch_info()` of the `ContractionTree` object was an empty list in this case.  Is there a way to resolve this error without decreasing the size of `open_indices`?

```
~/simulators/acqdp$ python3 examples/circuit_simulation.py entanglement_30.txt
(3_w,7)-aCMA-ES (mu_w=2.3,w_1=58%) in dimension 3 (seed=542818771, Fri Apr 15 09:37:11 2022)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      7 9.031326093199107e+00 1.0e+00 1.95e-01  2e-01  2e-01 0:12.7
Process 0 initial cost: cost = 9.057243475079245, cw = 30.0, num_slice = 0
Process 0 succeeded with cost = 9.030954605585789, cw = 28.0, num_slice = 2
cost = 9.030954605585789, cw = 28.0, num_slice = 2
Traceback (most recent call last):
  File "examples/circuit_simulation.py", line 157, in <module>
    tsk = tn.compile(order, **kwargs)
  File "/home/koova18/simulators/acqdp/acqdp/tensor_network/tensor_network.py", line 113, in compile
    return Compiler(**kwargs.get('compiler_params', {})).compile(self, order)
  File "/home/koova18/simulators/acqdp/acqdp/tensor_network/compiler.py", line 50, in compile
    res = self._generate_template(tn, scheme=scheme, **kwargs)
  File "/home/koova18/simulators/acqdp/acqdp/tensor_network/compiler.py", line 70, in _generate_template
    init_order, final_order = self._order_patch(tn_copy.copy(), order, split,
  File "/home/koova18/simulators/acqdp/acqdp/tensor_network/compiler.py", line 220, in _order_patch
    final_order = self._patch_order(tn_copy, final_order)
  File "/home/koova18/simulators/acqdp/acqdp/tensor_network/compiler.py", line 258, in _patch_order
    res = tree.patch(self.patch_size)
  File "/home/koova18/simulators/acqdp/acqdp/tensor_network/contraction_tree.py", line 281, in patch
    self.merge_nodes(width)
  File "/home/koova18/simulators/acqdp/acqdp/tensor_network/contraction_tree.py", line 178, in merge_nodes
    if len(br[1]) >= len(br[2]):
IndexError: list index out of range
```

**Comment by cupjinhuang** [comment]
Hello [ChienKaiMa](https://github.com/ChienKaiMa),

Thanks for pointing out this issue. The problem might not be directly related to the number of open indices, but is more likely due to a tensor network structure that triggered some corner case in the program.

Could you please provide the file `entanglement_30.txt` that reproduces this error? 

Cupjin

**Comment by ChienKaiMa** [comment]
I have difficulties attaching files right here, so I forked the repository and committed the modified code and circuit files in use in https://github.com/ChienKaiMa/acqdp/commit/fce402e48d573372ff3105d6101132abc12030d2

**Comment by cupjinhuang** [comment]
Hello @ChienKaiMa,

I have changed the logic such that the corresponding optimization is not performed in such cases in order not to raise the error.

Please let me know if this helps.

Cupjin
